# Generated by Django 5.1.6 on 2025-10-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailychallenge',
            name='max_progress',
            field=models.IntegerField(default=1),
        ),
    ]
