# Generated by Django 5.1.6 on 2025-08-14 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listeningexercise",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="readingpassage",
            options={"ordering": ["title"]},
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="difficulty",
        ),
        migrations.RemoveField(
            model_name="listeningexercise",
            name="difficulty",
        ),
        migrations.RemoveField(
            model_name="readingpassage",
            name="difficulty",
        ),
        migrations.RemoveField(
            model_name="word",
            name="difficulty",
        ),
    ]
