# Generated by Django 5.1.6 on 2025-09-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="lesson_sequence",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Sequence of content types in the lesson",
            ),
        ),
    ]
