# Generated by Django 5.1.6 on 2025-09-16 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ["landmark", "order"]},
        ),
        migrations.RenameField(
            model_name="lesson",
            old_name="city",
            new_name="landmark",
        ),
        migrations.AlterUniqueTogether(
            name="lesson",
            unique_together={("landmark", "order")},
        ),
    ]
