# Generated by Django 5.1.6 on 2025-10-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lesson_lesson_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audio_url', models.URLField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='lesson',
        ),
        migrations.AlterUniqueTogether(
            name='userlessonprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userlessonprogress',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='userlessonprogress',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdventureLessonContent',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='UserLessonProgress',
        ),
    ]
