# Generated by Django 5.1.6 on 2025-09-14 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryPlaces",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="places",
                        to="lessons.country",
                    ),
                ),
            ],
            options={
                "ordering": ["country", "name"],
                "unique_together": {("country", "name")},
            },
        ),
        migrations.DeleteModel(
            name="City",
        ),
    ]
