# Generated by Django 5.1.6 on 2025-10-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_audio_remove_exercise_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_url',
            field=models.CharField(max_length=200),
        ),
    ]
