# Generated by Django 5.1.6 on 2025-10-09 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0004_alter_audio_audio_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="audio",
            old_name="description",
            new_name="text",
        ),
    ]
