# Generated by Django 5.1.6 on 2025-09-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0005_lesson"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sentence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentence", models.TextField()),
                ("translation", models.TextField()),
            ],
            options={
                "ordering": ["sentence"],
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="vocabularies",
            field=models.ManyToManyField(
                blank=True, related_name="lessons", to="lessons.vocabulary"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="sentences",
            field=models.ManyToManyField(
                blank=True, related_name="lessons", to="lessons.sentence"
            ),
        ),
    ]
