# Generated by Django 5.1.6 on 2025-10-09 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0005_rename_description_audio_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="audio",
            options={"ordering": ["text"]},
        ),
        migrations.RemoveField(
            model_name="audio",
            name="title",
        ),
    ]
