# Generated by Django 5.1.6 on 2025-09-14 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0006_sentence_lesson_vocabularies_lesson_sentences"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="level",
        ),
    ]
