# Generated by Django 5.1.6 on 2025-10-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0006_alter_audio_options_remove_audio_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
