# Generated by Django 5.1.6 on 2025-10-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0007_alter_audio_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="text",
            field=models.TextField(default="", max_length=500),
        ),
    ]
