# Generated by Django 5.1.6 on 2025-09-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0007_remove_lesson_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="updated_at",
        ),
    ]
