# Generated by Django 5.1.6 on 2025-09-14 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0008_remove_lesson_created_at_remove_lesson_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lessons.country",
            ),
        ),
    ]
