# Generated by Django 5.1.6 on 2025-10-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_alter_audio_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='audios',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='lessons.audio'),
        ),
    ]
