# Generated by Django 5.1.6 on 2025-09-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0009_lesson_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vocabulary",
            name="example_sentence",
        ),
    ]
