# Generated by Django 5.1.6 on 2025-10-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_lesson_audios'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='use_of_spanish',
            field=models.IntegerField(default=0, help_text='Number of use of Spanish exercises in the lesson'),
        ),
    ]
