# Generated by Django 5.1.6 on 2025-09-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0010_remove_vocabulary_example_sentence"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vocabulary",
            name="definition",
        ),
    ]
