# Generated by Django 5.1.6 on 2025-10-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0010_lesson_use_of_spanish"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="adventure_order",
            field=models.IntegerField(default=1),
        ),
    ]
