# Generated by Django 5.1.6 on 2025-09-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0011_remove_vocabulary_definition"),
    ]

    operations = [
        migrations.AddField(
            model_name="vocabulary",
            name="example_sentence",
            field=models.TextField(blank=True),
        ),
    ]
