# Generated by Django 5.1.6 on 2025-10-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0011_lesson_adventure_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="landmark",
            name="adventure_order",
            field=models.IntegerField(default=1),
        ),
    ]
