# Generated by Django 5.1.6 on 2025-10-27 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0012_landmark_adventure_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="landmark",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="lessons.landmark",
            ),
        ),
    ]
