# Generated by Django 5.1.6 on 2025-09-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0012_vocabulary_example_sentence"),
    ]

    operations = [
        migrations.AddField(
            model_name="vocabulary",
            name="conjugation",
            field=models.TextField(blank=True),
        ),
    ]
