# Generated by Django 5.1.6 on 2025-10-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0013_alter_lesson_landmark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="landmark",
            field=models.CharField(max_length=50),
        ),
    ]
