# Generated by Django 5.1.6 on 2025-10-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0015_alter_lesson_landmark"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landmark",
            name="adventure_order",
        ),
        migrations.AddField(
            model_name="country",
            name="adventure_order",
            field=models.IntegerField(default=1),
        ),
    ]
