# Generated by Django 5.1.6 on 2025-10-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0016_remove_landmark_adventure_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="landmark",
            name="adventure_order",
            field=models.IntegerField(default=1),
        ),
    ]
