# Generated by Django 5.1.6 on 2025-10-28 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0017_landmark_adventure_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="country",
            name="adventure_order",
        ),
        migrations.RemoveField(
            model_name="landmark",
            name="adventure_order",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="adventure_order",
        ),
        migrations.DeleteModel(
            name="AdventureLesson",
        ),
    ]
