# Generated by Django 5.1.6 on 2025-11-10 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0018_remove_country_adventure_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vocabulary",
            name="audio_url",
        ),
    ]
