# Generated by Django 5.1.6 on 2025-11-14 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0019_remove_vocabulary_audio_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vocabulary",
            name="conjugation",
        ),
        migrations.RemoveField(
            model_name="vocabulary",
            name="example_sentence",
        ),
        migrations.RemoveField(
            model_name="vocabulary",
            name="pronunciation",
        ),
    ]
