# Generated by Django 5.1.6 on 2025-11-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0020_remove_vocabulary_conjugation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="content",
        ),
    ]
