# Generated by Django 5.1.6 on 2025-11-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0021_remove_lesson_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="country_order",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
