# Generated by Django 5.1.6 on 2025-09-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country_lessons_progress",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
