# Generated by Django 5.1.6 on 2025-09-16 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="city_lessons_progress",
            new_name="landmark_lessons_progress",
        ),
    ]
