# Generated by Django 5.1.6 on 2025-08-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="day_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="expercience",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="level",
            field=models.IntegerField(default=1),
        ),
    ]
