# Generated by Django 5.1.6 on 2025-10-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sentences_learned",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="user",
            name="words_learned",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
