# Generated by Django 5.1.6 on 2025-08-11 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_user_day_streak_user_expercience_user_level"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="day_streak",
            new_name="days_streak",
        ),
    ]
