# Generated by Django 5.1.6 on 2025-10-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_sentences_learned_alter_user_words_learned'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_listening_practice_count',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='user',
            name='default_random_practice_count',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='user',
            name='default_sentences_practice_count',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='user',
            name='default_vocabulary_practice_count',
            field=models.IntegerField(default=20),
        ),
    ]
