# Generated by Django 5.1.6 on 2025-09-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_user_country_lessons_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="city_lessons_progress",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
