# Generated by Django 5.1.6 on 2025-10-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_default_listening_practice_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_listening_practice_count',
            field=models.IntegerField(default=10),
        ),
    ]
