# Generated by Django 5.1.6 on 2025-08-11 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_rename_day_streak_user_days_streak"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="expercience",
            new_name="experience",
        ),
    ]
