# Generated by Django 5.1.6 on 2025-10-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_user_default_listening_practice_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='default_sentences_practice_count',
        ),
        migrations.AddField(
            model_name='user',
            name='default_sentence_practice_count',
            field=models.IntegerField(default=10),
        ),
    ]
