# Generated by Django 5.1.6 on 2025-08-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_rename_expercience_user_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="adventure_progress",
            field=models.IntegerField(default=0),
        ),
    ]
