# Generated by Django 5.1.6 on 2025-08-11 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_user_adventure_progress"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("icon", models.CharField(default="⭐", max_length=10)),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("experience", "Experience Points"),
                            ("level", "Level"),
                            ("streak", "Days Streak"),
                            ("adventure_progress", "Adventure Progress"),
                            ("custom", "Custom Logic"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "condition_value",
                    models.IntegerField(help_text="Target value for the condition"),
                ),
                (
                    "points_reward",
                    models.IntegerField(
                        default=10, help_text="XP bonus for earning this achievement"
                    ),
                ),
                (
                    "is_hidden",
                    models.BooleanField(default=False, help_text="Hidden until earned"),
                ),
            ],
            options={
                "ordering": ["condition_value", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.achievement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-earned_at"],
                "unique_together": {("user", "achievement")},
            },
        ),
    ]
