# Generated by Django 5.1.6 on 2025-10-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_user_default_sentences_practice_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='audio_learned',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
