# Generated by Django 5.1.6 on 2025-08-12 07:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_achievement_userachievement"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="achievement",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="userachievement",
            options={},
        ),
        migrations.RemoveField(
            model_name="achievement",
            name="condition_type",
        ),
        migrations.RemoveField(
            model_name="achievement",
            name="condition_value",
        ),
        migrations.RemoveField(
            model_name="achievement",
            name="is_hidden",
        ),
        migrations.RemoveField(
            model_name="achievement",
            name="points_reward",
        ),
        migrations.RemoveField(
            model_name="userachievement",
            name="earned_at",
        ),
        migrations.AddField(
            model_name="achievement",
            name="experience_award",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="achievement",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="achievement",
            name="users",
            field=models.ManyToManyField(
                related_name="achievements",
                through="base.UserAchievement",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userachievement",
            name="earned_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="icon",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="userachievement",
            name="achievement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="earned_by",
                to="base.achievement",
            ),
        ),
        migrations.AlterField(
            model_name="userachievement",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="earned_achievements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
