# Generated by Django 5.1.6 on 2025-10-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_user_audio_learned'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='use_of_spanish',
            field=models.FloatField(default=0.0),
        ),
    ]
