# Generated by Django 5.1.6 on 2025-10-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_user_use_of_spanish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='use_of_spanish',
            field=models.IntegerField(default=0),
        ),
    ]
