# Generated by Django 5.1.6 on 2025-08-12 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_alter_achievement_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userachievement",
            name="earned_date",
        ),
    ]
