# Generated by Django 5.1.6 on 2025-08-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_remove_userachievement_earned_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="words_learned",
            field=models.IntegerField(default=0),
        ),
    ]
