# Generated by Django 5.1.6 on 2025-10-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_user_use_of_spanish'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passports_earned',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
