# Generated by Django 5.1.6 on 2025-10-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_user_passports_earned"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatars/default_avatar.png",
                null=True,
                upload_to="avatars/",
            ),
        ),
    ]
