# Generated by Django 5.1.6 on 2025-08-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_user_words_learned"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="activity_days",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="last_activity_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
