# Generated by Django 5.1.6 on 2025-10-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="static/avatars/default_avatar.png",
                null=True,
                upload_to="static/avatars/",
            ),
        ),
    ]
