# Generated by Django 5.1.6 on 2025-10-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="images/avatars/default_avatar.png",
                null=True,
                upload_to="images/avatars/",
            ),
        ),
    ]
