# Generated by Django 5.1.6 on 2025-10-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="highest_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatars/default_avatar.png",
                null=True,
                upload_to="avatars/",
            ),
        ),
    ]
