# Generated by Django 5.1.6 on 2025-10-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_user_highest_streak_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_challenges',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
