# Generated by Django 5.1.6 on 2025-10-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_user_daily_challenges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='daily_challenges',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
