# Generated by Django 5.1.6 on 2025-10-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0016_alter_user_daily_challenges"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_daily_challenge_creation",
            field=models.DateField(blank=True, null=True),
        ),
    ]
