# Generated by Django 5.1.6 on 2025-10-28 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0017_user_last_daily_challenge_creation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="last_daily_challenge_creation",
            new_name="daily_challenges_creation_date",
        ),
    ]
