# Generated by Django 5.1.6 on 2025-11-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "base",
            "0018_rename_last_daily_challenge_creation_user_daily_challenges_creation_date",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="levels",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
