# Generated by Django 5.1.6 on 2025-11-02 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0019_user_levels"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="achievement",
            name="is_active",
        ),
    ]
