# Generated by Django 5.1.6 on 2025-11-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0020_remove_achievement_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="code",
            field=models.CharField(
                blank=True, default="", max_length=50, null=True, unique=True
            ),
        ),
    ]
