# Generated by Django 5.1.6 on 2025-11-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0022_alter_achievement_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="code",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
