# Generated by Django 5.1.6 on 2025-11-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0023_alter_achievement_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="daily_challenges_completed",
            field=models.BooleanField(default=False),
        ),
    ]
