# Generated by Django 5.1.6 on 2025-11-10 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0024_user_daily_challenges_completed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="levels",
        ),
    ]
